// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _4._Booking_AppointmentSystem.Models;

#nullable disable

namespace _4._Booking_AppointmentSystem.Migrations
{
    [DbContext(typeof(BookingContext))]
    partial class BookingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_4._Booking_AppointmentSystem.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerNotes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TimeSlot")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("_4._Booking_AppointmentSystem.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Professional clinical and medical consultations",
                            Icon = "heart-pulse",
                            Name = "Healthcare & Clinics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Premium styling, cosmetics, and relaxation therapies",
                            Icon = "scissors",
                            Name = "Beauty Salons & Spa"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Professional strategy meetings and career coaching",
                            Icon = "briefcase",
                            Name = "Business Consulting"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Therapeutic bodywork, yoga, and meditation sessions",
                            Icon = "flower1",
                            Name = "Holistic Wellness"
                        });
                });

            modelBuilder.Entity("_4._Booking_AppointmentSystem.Models.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Providers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Dr. Sarah holds a PhD in Cardiovascular Sciences from Johns Hopkins, boasting over 12 years of clinical research and practice.",
                            Email = "dr.sarah@bookingsystem.com",
                            ImagePath = "/images/provider-1.jpg",
                            Name = "Dr. Sarah Jenkins",
                            Phone = "+1 555-0101",
                            Rating = 4.9000000000000004,
                            Title = "Senior Cardiologist"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Dr. Ahmed specializes in advanced implantology and aesthetic smile makeovers with over 8 years in digital dentistry.",
                            Email = "dr.ahmed@bookingsystem.com",
                            ImagePath = "/images/provider-2.jpg",
                            Name = "Dr. Ahmed Mansour",
                            Phone = "+1 555-0102",
                            Rating = 4.7999999999999998,
                            Title = "Specialist Cosmetic Dentist"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Maria is a certified master colorist, trained in Paris, renowned for creating personalized shades and modern haircuts.",
                            Email = "maria.l@bookingsystem.com",
                            ImagePath = "/images/provider-3.jpg",
                            Name = "Maria Lopez",
                            Phone = "+1 555-0201",
                            Rating = 4.7000000000000002,
                            Title = "Master Hair Stylist & Colorist"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "John is an ICF-certified coach helping professionals scale business startups and unlock their career potentials.",
                            Email = "john.d@bookingsystem.com",
                            ImagePath = "/images/provider-4.jpg",
                            Name = "John Davis",
                            Phone = "+1 555-0301",
                            Rating = 5.0,
                            Title = "Executive Life & Business Coach"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Yasmine has studied eastern relaxation therapies in Bali, specializing in trigger point release and hot stone body wellness.",
                            Email = "yasmine.e@bookingsystem.com",
                            ImagePath = "/images/provider-5.jpg",
                            Name = "Yasmine El-Amin",
                            Phone = "+1 555-0401",
                            Rating = 4.9000000000000004,
                            Title = "Holistic Therapist & Masseur"
                        });
                });

            modelBuilder.Entity("_4._Booking_AppointmentSystem.Models.ProviderSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("ProviderSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            ProviderId = 1,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            ProviderId = 1,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            ProviderId = 1,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            ProviderId = 1,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            ProviderId = 1,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            ProviderId = 2,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            ProviderId = 2,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            ProviderId = 2,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            ProviderId = 2,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            ProviderId = 2,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 11,
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            ProviderId = 3,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 12,
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            ProviderId = 3,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 13,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            ProviderId = 3,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 14,
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            ProviderId = 3,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 15,
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            ProviderId = 3,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 16,
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            ProviderId = 4,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 17,
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            ProviderId = 4,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 18,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            ProviderId = 4,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 19,
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            ProviderId = 4,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 20,
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            ProviderId = 4,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 21,
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            ProviderId = 5,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 22,
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            ProviderId = 5,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 23,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            ProviderId = 5,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 24,
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            ProviderId = 5,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 25,
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            ProviderId = 5,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("_4._Booking_AppointmentSystem.Models.ProviderService", b =>
                {
                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("ProviderId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ProviderServices");

                    b.HasData(
                        new
                        {
                            ProviderId = 1,
                            ServiceId = 3
                        },
                        new
                        {
                            ProviderId = 2,
                            ServiceId = 1
                        },
                        new
                        {
                            ProviderId = 2,
                            ServiceId = 2
                        },
                        new
                        {
                            ProviderId = 3,
                            ServiceId = 4
                        },
                        new
                        {
                            ProviderId = 3,
                            ServiceId = 5
                        },
                        new
                        {
                            ProviderId = 3,
                            ServiceId = 6
                        },
                        new
                        {
                            ProviderId = 4,
                            ServiceId = 7
                        },
                        new
                        {
                            ProviderId = 4,
                            ServiceId = 8
                        },
                        new
                        {
                            ProviderId = 5,
                            ServiceId = 9
                        },
                        new
                        {
                            ProviderId = 5,
                            ServiceId = 10
                        });
                });

            modelBuilder.Entity("_4._Booking_AppointmentSystem.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Comprehensive medical consultation and general checkup.",
                            DurationMinutes = 30,
                            Name = "General Physician Checkup",
                            Price = 60.00m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Plaque removal, teeth polishing, and deep hygiene assessment.",
                            DurationMinutes = 45,
                            Name = "Professional Dental Cleaning",
                            Price = 90.00m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Advanced ECG test and cardiologist specialist evaluation.",
                            DurationMinutes = 60,
                            Name = "Cardiovascular Consultation",
                            Price = 180.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Custom haircut, wash, styling, and hot towel finish.",
                            DurationMinutes = 30,
                            Name = "Signature Men's Haircut",
                            Price = 35.00m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "High-end hair coloring, toning, deep conditioning, and blow dry.",
                            DurationMinutes = 120,
                            Name = "Women's Balayage & Styling",
                            Price = 150.00m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Deep cleansing, exfoliation, and hydration infusion.",
                            DurationMinutes = 60,
                            Name = "HydraFacial Skin Treatment",
                            Price = 95.00m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "1-on-1 strategic growth and scale planning session.",
                            DurationMinutes = 60,
                            Name = "Corporate Strategy Consult",
                            Price = 250.00m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Resume audit, interview Prep, and leadership path coaching.",
                            DurationMinutes = 45,
                            Name = "Executive Career Coaching",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Description = "Focus on releasing chronic muscle tension and body knots.",
                            DurationMinutes = 60,
                            Name = "Deep Tissue Muscle Massage",
                            Price = 85.00m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Description = "Heated basalt stones massage to melt away stress and fatigue.",
                            DurationMinutes = 75,
                            Name = "Premium Hot Stone Therapy",
                            Price = 110.00m
                        });
                });

            modelBuilder.Entity("_4._Booking_AppointmentSystem.Models.Appointment", b =>
                {
                    b.HasOne("_4._Booking_AppointmentSystem.Models.Provider", "Provider")
                        .WithMany("Appointments")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_4._Booking_AppointmentSystem.Models.Service", "Service")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("_4._Booking_AppointmentSystem.Models.ProviderSchedule", b =>
                {
                    b.HasOne("_4._Booking_AppointmentSystem.Models.Provider", "Provider")
                        .WithMany("Schedules")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("_4._Booking_AppointmentSystem.Models.ProviderService", b =>
                {
                    b.HasOne("_4._Booking_AppointmentSystem.Models.Provider", "Provider")
                        .WithMany("ProviderServices")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_4._Booking_AppointmentSystem.Models.Service", "Service")
                        .WithMany("ProviderServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("_4._Booking_AppointmentSystem.Models.Service", b =>
                {
                    b.HasOne("_4._Booking_AppointmentSystem.Models.Category", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("_4._Booking_AppointmentSystem.Models.Category", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("_4._Booking_AppointmentSystem.Models.Provider", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ProviderServices");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("_4._Booking_AppointmentSystem.Models.Service", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ProviderServices");
                });
#pragma warning restore 612, 618
        }
    }
}
